# Site settings

title: All About Dennis
SEOTitle: 曾旻的博客 | Dennis Min Zeng 
header-img: img/home-bg.jpg
email: dennisminzeng@gmail.com
description: "Interesting things related to tech, AI and the world in general"
keyword: "曾旻, 博客, 个人网站, 互联网, AI, Tech"
url: "http://www.dennisminzeng.com"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
RSS: false
weibo_username:     fifastar01
zhihu_username:     zengmin
github_username:    fifastar01
twitter_username:  fifastar01
facebook_username:  dennismin.zeng
# linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
disqus_username: www-dennisminzeng-com
disqus_share: true
# Duoshuo settings
duoshuo_username: dennisminzeng
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: false                     # set to false if you want to use Comment without Sharing




# Analytics settings
# Baidu Analytics
# ba_track_id: 4cc1f2d8f3067386cc5cdb626a202900
# Google Analytics
# ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
# ga_domain: huangxuan.me



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "No free lunch"
sidebar-avatar: /img/avatar-zeng.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 3              # A tag will be featured if the size of it is more than this condition value



# Friends
friends: [
    {
        title: "星云",
        href: "http://www.dennisminzeng.com"
    },{
        title: "AVC",
        href: "http://avc.com/"
    },{
        title: "Ben Evans",
        href: "http://ben-evans.com/"
    },{
        title: "Karpathy",
        href: "http://karpathy.github.io/"
    },{
        title: "AI Playbook",
        href: "http://aiplaybook.a16z.com/"
    }
]
